services:

   nginx:
     environment:
      - NGINX_PORT=8600
     ports: 
         - 8600:8600
     networks:
         - shared-swarm-net-dev

   elasticsearch:
     networks:
         - shared-swarm-net-dev

   logstash:
      networks:
         - shared-swarm-net-dev
    
   kibana:
     networks:
         - shared-swarm-net-dev

      
