
configs:
     nginx_conf:
       file: /home/${VM_USER}/${APPNAME}/nginx/nginx.${TARGETENV}.conf

services:


  nginx:
       image: nginx:alpine
       deploy:
         restart_policy:
            condition: on-failure
         placement:
          constraints: [node.labels.role == worker3]
       command: ["/bin/sh", "-c", "envsubst < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
       environment:
         - KIBANA_PORT=5601
         - stdoutPath=/var/log/${APPNAME}-nginx/combined.log
         - stderrPath=/var/log/${APPNAME}-nginx/error.log
         - AZURE_VM_DOMAIN=${AZURE_VM_DOMAIN} # exposed from github actions but must be declared here to access in conf file
       configs: 
         - source: nginx_conf 
           target: /etc/nginx/templates/default.conf.template
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      restart_policy:
          condition: on-failure
      placement:
          constraints: [node.labels.role == worker3]
      resources:
        limits:
          memory: 2g
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g  # Elasticsearch heap size
      - bootstrap.memory_lock=true
      - indices.memory.index_buffer_size=10%
      - indices.breaker.total.limit=70%
   
  logstash:
    image: ${DOCKERHUB_USER}/${APPNAME}-logstash:${TAG}
    deploy:
      restart_policy:
          condition: on-failure
      placement:
          constraints: [node.labels.role == worker3]
      resources:
        limits:
          memory: 1g
    environment:
       - LS_JAVA_OPTS=-Xms512m -Xmx512m  # Logstash heap size


  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    deploy:
      restart_policy:
          condition: on-failure
      placement:
          constraints: [node.labels.role == worker3]
      resources:
        limits:
          memory: 1g
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
      - TELEMETRY_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
      - XPACK_GRAPH_ENABLED=false
  
  
networks:
   shared-swarm-net-dev:
      external: true
   shared-swarm-net-prod:
      external: true

volumes:
  esdata: